# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XTcGbiYMQyezAWr1ClX6hvlU6aMitP4u
"""

#Mutiplication

a= int(input("Enter the number ")) 
b= int(input("Enter the number ")) 
c= a*b
print(" The answer is ", c)

#Division

a= int(input("Enter the number ")) 
b= int(input("Enter the number ")) 
c= a/b
print(" The answer is ", c)

#Subraction

a= int(input("Enter the number ")) 
b= int(input("Enter the number ")) 
c= a-b
print(" The answer is ", c)